name: Build Vue frontend

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'npm'
    - run: yarn install
    - run: yarn run build
    - uses: actions/upload-pages-artifact@v3
      with:
        path: dist/
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
  
  pdf:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
    - uses: actions/checkout@v4
    - name: Generate PDF
      run: |
        docker run --rm \
          -e TARGET_URL="https://cv.denv.it" \
          -e PUPPETEER_ARGS="--no-sandbox" \
          -v ${{ github.workspace }}:/workspace \
          dvitali/cv-render:latest \
          /bin/sh -c "cp -r /app /tmp/app && cd /tmp/app && npm install && mkdir -p output && HOME=/tmp ./entrypoint.sh && cp output/cv.pdf /workspace/"
    - name: Archive CV PDF
      uses: actions/upload-artifact@v4
      with:
        name: cv
        path: cv.pdf
